POST http://localhost:5000/api/auth/add-member
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDE2Y2UxN2ZhZmQzM2UyOGY5Y2I1MiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0OTM5MTM0OCwiZXhwIjoxNjUwNjg3MzQ4fQ.fnRPsjOChaJJ5WRuOoUC_WpOyIJm1OynU-hqZQgbRVc

{
    "fullname": "test",
    "email": "test7@gmail.com",
    "password": "123123"
}

###

POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "admin.devplus@gmail.com",
    "password": "123123"
}

###

POST http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

###

